name: 2D Realtime Live Bot

on:
  schedule:
    - cron: '0 3 * * *'
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  run-nonstop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests firebase-admin pytz
      - name: Run Constant Loop
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          python -c "
          import subprocess, time
          start_time = time.time()
          while time.time() - start_time < 10800:
              subprocess.run(['python', 'update_data.py'])
              time.sleep(1)
          "
